import Head from 'next/head'
import Nav from './nav.js'
import React from 'react';
import clientPromise from '../lib/mongo.js'
export default function Home() {
  return (
    <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className = "container">
          <Nav></Nav>
        </div>
    </>
  )
}
/*  
export async function getServerSideProps(context) {
  try {
    const client = await clientPromise;
    const db = await client.db();
    const dbProps = {}
    return {
        props: { dbProps: JSON.parse(JSON.stringify(dbProps)) } 
    };
  }
  catch(err) {
    console.error(err);
  }
}; */