import Head from 'next/head'
import Nav from './nav.js'
import React from 'react';
export default function Home() {
  return (
    <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
        </Head>
        <div className = "container">
          <Nav></Nav>
        </div>
    </>
  )
}
